artifact_location: /Users/sarvesh/Desktop/GitHub/lego-minifigure-finder/notebooks/mlflow/0
creation_time: 1758689736458
experiment_id: '0'
last_update_time: 1758689736458
lifecycle_stage: active
name: Default
