artifact_location: /Users/sarvesh/Desktop/GitHub/lego-minifigure-finder/notebooks/mlflow/770496662894020587
creation_time: 1758689736465
experiment_id: '770496662894020587'
last_update_time: 1758689736465
lifecycle_stage: active
name: lego-minifig-test
